# Generated by Django 5.0.3 on 2025-06-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='部门状态'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='route_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='路由名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '停用')], default='1', max_length=1, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
