# Generated by Django 5.0.3 on 2025-07-02 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_dept_status_alter_menu_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_depts', to='system.dept', verbose_name='部门')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_depts', to='system.role', verbose_name='角色')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '角色部门',
                'verbose_name_plural': '角色部门',
                'db_table': 'sys_role_dept',
            },
        ),
    ]
