# Generated by Django 5.0.3 on 2025-07-31 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_menu_active_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志')),
                ('source_file_name', models.CharField(default='', max_length=255, verbose_name='源文件名')),
                ('file_type', models.CharField(choices=[('1', 'TXT'), ('2', 'Excel'), ('3', 'CSV'), ('4', 'JSON'), ('5', 'SQL')], default='1', max_length=255, verbose_name='文件类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('file', models.FileField(null=True, upload_to='D:\\code\\xadmin\\backend_django\\uploads', verbose_name='文件')),
                ('file_md5', models.CharField(max_length=255, unique=True, verbose_name='文件md5')),
                ('biz_type', models.CharField(choices=[('1', '导入接口文件'), ('2', '导入元数据文件'), ('3', '导入表映射文件')], default='1', max_length=1, verbose_name='业务类型')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_upload_file_info',
            },
        ),
    ]
