# Generated by Django 5.0.3 on 2025-07-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_uploadfileinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='active_menu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='激活菜单'),
        ),
    ]
