@host = http://localhost:8000


###
# @name getRouters
GET {{host}}/api/getRouters
Authorization: Bearer {{accessToken}}


###
# @name getMenuList
GET {{host}}/api/system/menu?noPage=1
Authorization: Bearer {{accessToken}}


