@host = http://localhost:8000


@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzI1NDA4NiwiaWF0IjoxNzUzMTY3Njg2LCJqdGkiOiI2Yzg2Y2IwY2JjYzU0MmJiOTA0NGEzODdmZTNlMzgyNCIsInVzZXJfaWQiOjEsInV1aWQiOiJhY2Y5YzM3OC0yZjU2LTQ5OWItOWNiMy0wMjg0NTFkZmU4NDIifQ.mhHXiSo455C6bHRCY5qSwBNTE6IpXDkAeFi9hNwrT4g


###
# @name getRouters
GET {{host}}/api/getRouters
Authorization: Bearer {{accessToken}}


###
# @name getMenuList
GET {{host}}/api/system/menu?noPage=1
Authorization: Bearer {{accessToken}}


