# Generated by Django 5.0.3 on 2025-07-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_interfacefield_del_flag_interfaceinfo_del_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacequerylog',
            name='query_params',
            field=models.TextField(blank=True, null=True, verbose_name='查询参数'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='alarm_type',
            field=models.CharField(choices=[('0', '否'), ('1', '邮件'), ('2', '短信'), ('3', '钉钉'), ('4', '企业微信'), ('5', '电话'), ('6', '飞书')], default='0', max_length=1, verbose_name='报警类型'),
        ),
    ]
