# Generated by Django 5.0.3 on 2025-07-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_interfaceinfo_interface_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacequerylog',
            name='interface_total_sql',
            field=models.TextField(null=True, verbose_name='接口总sql'),
        ),
    ]
