# Generated by Django 5.0.3 on 2025-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_delete_uploadfileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='interface_datasource',
            field=models.IntegerField(blank=True, null=True, verbose_name='数据源ID'),
        ),
    ]
