version: '3'

services:
  StarRocks:
    image: starrocks/allin1-ubuntu:3.2.6
    ports:
      - "8080:8080"
      - "9030:9030"
  MySQL:
    image: debezium/example-mysql:1.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  presto:
    image: prestodb/presto:0.292
    container_name: presto
    ports:
      - "8084:8084"
    volumes:
      - ./prestodb/config.properties:/opt/presto-server/etc/config.properties
      - ./prestodb/jvm.config:/opt/presto-server/etc/jvm.config
    restart: unless-stopped