# Generated by Django 5.0.3 on 2025-06-05 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='system.post', verbose_name='岗位')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户岗位关联',
                'db_table': 'sys_user_post',
            },
        ),
    ]
