# Generated by Django 5.0.3 on 2025-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_roledept'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active_menu',
            field=models.CharField(blank=True, db_comment='激活菜单', max_length=255, null=True, verbose_name='激活菜单'),
        ),
    ]
