# Generated by Django 5.0.3 on 2025-07-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_uploadfileinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadfileinfo',
            table='sys_upload_file_info',
        ),
    ]
