# Generated by Django 5.0.3 on 2025-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_menu_active_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfileinfo',
            name='file',
            field=models.FileField(null=True, upload_to='./uploads', verbose_name='文件'),
        ),
    ]
