# Generated by Django 5.0.3 on 2025-05-22 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('type', models.CharField(default='mysql', max_length=50, verbose_name='数据源类型')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('database', models.CharField(max_length=100, verbose_name='数据库名')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'ds_datasource',
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sql', models.TextField(verbose_name='SQL语句')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='执行状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(default=0, verbose_name='执行时间(秒)')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果行数')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.datasource', verbose_name='数据源')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '查询日志',
                'verbose_name_plural': '查询日志',
                'db_table': 'ds_query_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
