@host = http://localhost:8000

###
# @name login
POST {{host}}/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "code":"A3BS",
  "uuid":"1f3df7a4-9b7e-4816-8c76-8ac41205d88f"
}



###
# 获取数据源
GET {{host}}/api/datasources/ HTTP/1.1
Authorization: Bearer {{login.response.body.$.token}}

###
#
GET {{host}}/api/datasources/types/ HTTP/1.1
Authorization: Bearer {{login.response.body.$.token}}

###
# 添加数据源
POST {{host}}/api/datasources/ HTTP/1.1
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
    "name": "租户库",
    "type": "mysql",
    "url": "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true",
    "username": "root",
    "password": "123456",
    "host":  "localhost",
    "port":  "3306",
    "database":  "test"
}

###
#
POST {{host}}/api/datasources/1/query/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{login.response.body.$.token}}

sql=select%201


###
# 获取查询日志
GET {{host}}/api/querylogs/ HTTP/1.1
Authorization: Bearer {{login.response.body.$.token}}