@host = http://localhost:8000

### 
# @name login
# @description 登录
POST {{host}}/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456",
    "code": "X888",
    "uuid": "acf9c378-2f56-499b-9cb3-028451dfe842"
}



###
POST {{host}}/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MjgwNjIyNCwiaWF0IjoxNzUyNzE5ODI0LCJqdGkiOiJjNTg2MmE1NTM4MmE0MTg5OGY2Y2I5ZWI5NjYwNDI1ZSIsInVzZXJfaWQiOjEsInV1aWQiOiIzMTUzODE5Ny00YmIyLTRhNDktYmEzZS1hNjUyNGMxNDg0ODQifQ.xsZb_HZISfKKGU-ZyqVxyllLXI1b2_jA2Z2x98f0Kck





