@host = http://localhost:8000

###
# @name login
POST {{host}}/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "code":"N9RV",
  "uuid":"c68521ff-4052-474e-8c1e-15940c46e6e9"
}


###
# 获取列表
GET {{host}}/api/report/reports/ HTTP/1.1
Authorization: Bearer {{login.response.body.token}}


###
# 获取平台信息
GET {{host}}/api/report/platforms/?noPage=1&moduleId=1 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

### 
# 获取模块信息
GET {{host}}/api/report/modules/?noPage=1&platformId=1 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

###
# 获取report
GET {{host}}/api/report/reports/1/ HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

###
# 获取接口列表
GET {{host}}/api/report/interfaces/?noPage=1&report_id=2 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}


###
# 获取接口信息
GET {{host}}/api/report/interfaces/3/ HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

###
# 获取接口字段
GET {{host}}/api/report/interface-fields/?interface=1&noPage=1 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

###
# 获取接口查询日志
GET {{host}}/api/report/interface-logs/?page=1&page_size=10 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}


###
# 查询接口
POST {{host}}/api/report/execute-query/?interface_code=ads_xl_ai_account_exhibit_hall HTTP/1.1
Authorization:  Bearer {{login.response.body.token}}



###
# 测试接口
POST https://qyapitest.qiyucloud.com.cn/datacenter/reportdata/?interface_code=dim_tenant_xl_2 HTTP/1.1
Content-Type: application/json

{
    "interface_type": "2", 
    "total_type": "1", 
    "page_no": "2", 
    "page_size": 10, 
    "operate_type": "1"
}