@host = http://localhost:8000

# @name getCaptcha
GET {{host}}/api/captchaImage HTTP/1.1

###
# @name login
POST {{host}}/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "code":"A3BS",
  "uuid":"1f3df7a4-9b7e-4816-8c76-8ac41205d88f"
}

###

@token = {{login.response.body.token}}

###
GET {{host}}/api/system/dept HTTP/1.1
Authorization: Bearer {{token}}

###
# 用户请求
GET {{host}}/api/system/users HTTP/1.1
Authorization: Bearer {{token}}

###
# 用户详情
GET {{host}}/api/system/users/1 HTTP/1.1
Authorization: Bearer {{token}}

###
# 添加用户
POST {{host}}/api/system/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "xxxx",
  "password": "12345c6"
}

###
# 更新用户
PUT {{host}}/api/system/users/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "testusexr",
  "password": "newpassword",
  "dept_id": 103
}

###
# 搜索用户
GET {{host}}/api/system/users?pageNum=3&pageSize=10&deptId=104 HTTP/1.1
Authorization: Bearer {{token}}

###
# 用户菜单列表
GET {{host}}/api/system/menus/user_menus HTTP/1.1
Authorization: Bearer {{token}}


###
# 用户角色列表
GET {{host}}/api/system/roles HTTP/1.1
Authorization: Bearer {{token}}


###
GET {{host}}/api/getRouters HTTP/1.1
Authorization: Bearer {{token}}


###
GET {{host}}/api/system/dict/type HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{host}}/api/system/dict/data/type/sys_normal_disable HTTP/1.1
Authorization: Bearer {{token}}


###
GET {{host}}/api/system/users/deptTree HTTP/1.1
Authorization: Bearer {{token}}