# Generated by Django 5.0.3 on 2025-05-22 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface_name', models.CharField(max_length=255, verbose_name='接口名称')),
                ('interface_code', models.CharField(max_length=255, unique=True, verbose_name='接口编码')),
                ('interface_desc', models.TextField(blank=True, null=True, verbose_name='接口描述')),
                ('interface_db_type', models.CharField(max_length=255, verbose_name='数据库类型')),
                ('interface_db_name', models.CharField(max_length=255, verbose_name='数据库名称')),
                ('interface_sql', models.TextField(blank=True, null=True, verbose_name='接口sql')),
                ('is_total', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否合计')),
                ('total_sql', models.TextField(blank=True, null=True, verbose_name='合计sql')),
                ('is_paging', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否分页')),
                ('is_date_option', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否日期查询')),
                ('is_second_table', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='二级表头')),
                ('is_login_visit', models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否登陆验证')),
                ('alarm_type', models.CharField(choices=[('0', '否'), ('1', '邮件'), ('2', '短信'), ('3', '钉钉'), ('4', '企业微信'), ('5', '电话')], default='0', max_length=1, verbose_name='报警类型')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名称')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_interface_info',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InterfaceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface_para_code', models.CharField(max_length=255, verbose_name='接口参数编码')),
                ('interface_para_name', models.CharField(max_length=255, verbose_name='接口参数名称')),
                ('interface_para_position', models.IntegerField(verbose_name='接口参数位置')),
                ('interface_para_type', models.CharField(choices=[('1', '输入参数'), ('2', '输出参数')], max_length=255, verbose_name='接口参数类型')),
                ('interface_data_type', models.CharField(choices=[('1', '字符'), ('2', '整数'), ('3', '小数'), ('4', '百分比'), ('5', '无格式整数'), ('6', '无格式小数'), ('7', '无格式百分比'), ('8', '1位百分比'), ('9', '1位小数'), ('10', '年份'), ('11', '日期'), ('12', '月份'), ('13', '单选'), ('14', '多选'), ('15', '文本')], max_length=255, verbose_name='接口参数数据类型')),
                ('interface_para_default', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数默认值')),
                ('interface_para_rowspan', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True, verbose_name='接口参数跨行')),
                ('interface_parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数父级名称')),
                ('interface_parent_position', models.IntegerField(blank=True, null=True, verbose_name='接口参数父级位置')),
                ('interface_para_interface_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数接口编码')),
                ('interface_cascade_para', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数级联参数')),
                ('interface_show_flag', models.CharField(choices=[('1', '是'), ('0', '否')], default='1', max_length=255, verbose_name='接口参数是否显示')),
                ('interface_export_flag', models.CharField(choices=[('1', '是'), ('0', '否')], default='1', max_length=255, verbose_name='接口参数是否导出')),
                ('interface_show_desc', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], max_length=255, null=True, verbose_name='接口参数显示名称')),
                ('interface_para_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='接口参数描述')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.interfaceinfo', verbose_name='接口')),
            ],
            options={
                'db_table': 'report_interface_field',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InterfaceQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface_code', models.CharField(max_length=255, verbose_name='接口编码')),
                ('interface_sql', models.TextField(null=True, verbose_name='接口sql')),
                ('execute_start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='开始时间')),
                ('execute_end_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='结束时间')),
                ('execute_time', models.IntegerField(default=0, verbose_name='执行时间')),
                ('execute_result', models.TextField(null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(null=True, verbose_name='错误信息')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_interface_query_log',
                'ordering': ('-execute_start_time',),
            },
        ),
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='平台名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_platform_info',
            },
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='模块名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.platforminfo', verbose_name='平台')),
            ],
            options={
                'db_table': 'report_module_info',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='报表名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.moduleinfo', verbose_name='模块')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_report_info',
            },
        ),
        migrations.AddField(
            model_name='interfaceinfo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportinfo', verbose_name='报表'),
        ),
        migrations.CreateModel(
            name='TableColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_id', models.IntegerField(verbose_name='表id')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_table_column_mapping',
            },
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_name', models.CharField(max_length=255, verbose_name='表名')),
                ('table_desc', models.CharField(max_length=255, verbose_name='描述')),
                ('table_schema', models.CharField(default='', max_length=255, null=True, verbose_name='表模式')),
                ('schema_type', models.CharField(default='', max_length=255, verbose_name='模式类型')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_table_info',
                'ordering': ('id',),
                'unique_together': {('table_name', 'table_schema', 'schema_type')},
            },
        ),
        migrations.CreateModel(
            name='TableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_id', models.IntegerField(null=True, verbose_name='表id')),
                ('table_schema', models.CharField(max_length=255, null=True, verbose_name='表模式')),
                ('schema_type', models.CharField(max_length=255, null=True, verbose_name='模式类型')),
                ('table_name', models.CharField(max_length=255, null=True, verbose_name='表名')),
                ('src_table_id', models.IntegerField(null=True, verbose_name='源表id')),
                ('src_table_schema', models.CharField(max_length=255, null=True, verbose_name='源表模式')),
                ('src_schema_type', models.CharField(max_length=255, null=True, verbose_name='源模式类型')),
                ('src_table_name', models.CharField(max_length=255, null=True, verbose_name='源表名')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_table_mapping',
            },
        ),
        migrations.CreateModel(
            name='UploadFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_file_name', models.CharField(default='', max_length=255, verbose_name='源文件名')),
                ('file_type', models.CharField(choices=[('1', 'TXT'), ('2', 'Excel'), ('3', 'CSV'), ('4', 'JSON'), ('5', 'SQL')], default='1', max_length=255, verbose_name='文件类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('file', models.FileField(null=True, upload_to='upload_files', verbose_name='文件')),
                ('file_md5', models.CharField(max_length=255, unique=True, verbose_name='文件md5')),
                ('biz_type', models.CharField(choices=[('1', '导入接口文件'), ('2', '导入元数据文件'), ('3', '导入表映射文件')], default='1', max_length=1, verbose_name='业务类型')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'report_upload_file_info',
            },
        ),
        migrations.CreateModel(
            name='TableColumnInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('column_name', models.CharField(max_length=255, verbose_name='字段名')),
                ('column_desc', models.CharField(max_length=255, verbose_name='字段描述')),
                ('column_order', models.IntegerField(default=-1, null=True, verbose_name='字段排序')),
                ('data_type', models.CharField(max_length=255, verbose_name='字段数据类型')),
                ('data_length', models.IntegerField(null=True, verbose_name='字段长度')),
                ('column_key', models.CharField(max_length=255, null=True, verbose_name='字段约束')),
                ('is_nullable', models.CharField(max_length=255, null=True, verbose_name='是否为空')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updator', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.tableinfo')),
            ],
            options={
                'db_table': 'report_table_column',
                'ordering': ('column_order',),
                'unique_together': {('table', 'column_name')},
            },
        ),
    ]
