# Generated by Django 5.0.3 on 2025-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacefield',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='interfaceinfo',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='interfacequerylog',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='tablecolumninfo',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='tablecolumnmapping',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='tableinfo',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='tablemapping',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AddField(
            model_name='uploadfileinfo',
            name='del_flag',
            field=models.CharField(choices=[('0', '存在'), ('1', '删除')], default='0', max_length=1, verbose_name='删除标志'),
        ),
        migrations.AlterField(
            model_name='interfacefield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='interfacequerylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='moduleinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='platforminfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tablecolumninfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tablecolumnmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tablemapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='uploadfileinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
