# Generated by Django 5.0.3 on 2025-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_interfacequerylog_query_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceinfo',
            name='interface_datasource',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='数据源'),
        ),
    ]
