# Generated by Django 5.0.3 on 2025-07-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_interfacequerylog_interface_total_sql'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileInfo',
        ),
    ]
